development:
  adapter: mysql
  database: geoip_development
  user: YOUR USERNAME
  password: YOUR PASSWORD
production:
  adapter: mysql
  database: geoip_production
  user: YOUR USERNAME
  password: YOUR PASSWORD
test:
  adapter: mysql
  database: geoip_test
  user: YOUR USERNAME
  password: YOUR PASSWORD

