development:
  adapter: mysql
  database: geoip_development
  user: root
  password: blabli
production:
  adapter: mysql
  database: geoip_production
  user: root
  password: blabli
test:
  adapter: mysql
  database: geoip_test
  user: root
  password: blabli
